/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRangeProtocolFactory,
  IRangeProtocolFactoryInterface,
} from "../../../../contracts/range/interfaces/IRangeProtocolFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "uniPool",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "vault",
        type: "address",
      },
    ],
    name: "VaultCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "uniPool",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "vault",
        type: "address",
      },
    ],
    name: "VaultImplUpgraded",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "configData",
        type: "bytes",
      },
    ],
    name: "createVault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_vault",
        type: "address",
      },
      {
        internalType: "address",
        name: "_impl",
        type: "address",
      },
    ],
    name: "upgradeVault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_vaults",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "_impls",
        type: "address[]",
      },
    ],
    name: "upgradeVaults",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRangeProtocolFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IRangeProtocolFactoryInterface {
    return new Interface(_abi) as IRangeProtocolFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRangeProtocolFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRangeProtocolFactory;
  }
}
