/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as math from "./math";
export type { math };
export type { Address } from "./Address";
export type { Strings } from "./Strings";
