/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IContractIdentifier,
  IContractIdentifierInterface,
} from "../../../../../@axelar-network/axelar-gmp-sdk-solidity/contracts/interfaces/IContractIdentifier";

const _abi = [
  {
    inputs: [],
    name: "contractId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IContractIdentifier__factory {
  static readonly abi = _abi;
  static createInterface(): IContractIdentifierInterface {
    return new Interface(_abi) as IContractIdentifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IContractIdentifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IContractIdentifier;
  }
}
