/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface FullMathEchidnaTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkMulDiv"
      | "checkMulDivRounding"
      | "checkMulDivRoundingUp"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkMulDiv",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkMulDivRounding",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkMulDivRoundingUp",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkMulDiv",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkMulDivRounding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkMulDivRoundingUp",
    data: BytesLike
  ): Result;
}

export interface FullMathEchidnaTest extends BaseContract {
  connect(runner?: ContractRunner | null): FullMathEchidnaTest;
  waitForDeployment(): Promise<this>;

  interface: FullMathEchidnaTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkMulDiv: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish, d: BigNumberish],
    [void],
    "view"
  >;

  checkMulDivRounding: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish, d: BigNumberish],
    [void],
    "view"
  >;

  checkMulDivRoundingUp: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish, d: BigNumberish],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkMulDiv"
  ): TypedContractMethod<
    [x: BigNumberish, y: BigNumberish, d: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkMulDivRounding"
  ): TypedContractMethod<
    [x: BigNumberish, y: BigNumberish, d: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkMulDivRoundingUp"
  ): TypedContractMethod<
    [x: BigNumberish, y: BigNumberish, d: BigNumberish],
    [void],
    "view"
  >;

  filters: {};
}
