/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface TickBitmapEchidnaTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkNextInitializedTickWithinOneWordInvariants"
      | "flipTick"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkNextInitializedTickWithinOneWordInvariants",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "flipTick",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkNextInitializedTickWithinOneWordInvariants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flipTick", data: BytesLike): Result;
}

export interface TickBitmapEchidnaTest extends BaseContract {
  connect(runner?: ContractRunner | null): TickBitmapEchidnaTest;
  waitForDeployment(): Promise<this>;

  interface: TickBitmapEchidnaTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkNextInitializedTickWithinOneWordInvariants: TypedContractMethod<
    [tick: BigNumberish, lte: boolean],
    [void],
    "view"
  >;

  flipTick: TypedContractMethod<[tick: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkNextInitializedTickWithinOneWordInvariants"
  ): TypedContractMethod<[tick: BigNumberish, lte: boolean], [void], "view">;
  getFunction(
    nameOrSignature: "flipTick"
  ): TypedContractMethod<[tick: BigNumberish], [void], "nonpayable">;

  filters: {};
}
