/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface TickOverflowSafetyEchidnaTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "increaseFeeGrowthGlobal0X128"
      | "increaseFeeGrowthGlobal1X128"
      | "moveToTick"
      | "setPosition"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "increaseFeeGrowthGlobal0X128",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseFeeGrowthGlobal1X128",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moveToTick",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPosition",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "increaseFeeGrowthGlobal0X128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseFeeGrowthGlobal1X128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moveToTick", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPosition",
    data: BytesLike
  ): Result;
}

export interface TickOverflowSafetyEchidnaTest extends BaseContract {
  connect(runner?: ContractRunner | null): TickOverflowSafetyEchidnaTest;
  waitForDeployment(): Promise<this>;

  interface: TickOverflowSafetyEchidnaTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  increaseFeeGrowthGlobal0X128: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  increaseFeeGrowthGlobal1X128: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  moveToTick: TypedContractMethod<[target: BigNumberish], [void], "nonpayable">;

  setPosition: TypedContractMethod<
    [
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidityDelta: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "increaseFeeGrowthGlobal0X128"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "increaseFeeGrowthGlobal1X128"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "moveToTick"
  ): TypedContractMethod<[target: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPosition"
  ): TypedContractMethod<
    [
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidityDelta: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
