/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20 from "./ERC20";
export type { erc20 };
export type { USDC } from "./USDC";
export type { WETH } from "./WETH";
